#!/usr/bin/env python
# -*- coding:utf8 -*-

import subprocess
import botocore.session
import json
from sys import exit,argv
import jmespath


try:
    session = botocore.session.get_session()
    client = session.create_client('ec2', region_name='eu-west-1')
    full_instances = client.describe_instances()
except:
    print "error reading instances"
    exit(1)

instances = jmespath.search('Reservations[].Instances[].{id: InstanceId,tags: Tags,private_ip: PrivateIpAddress,private_dns: PrivateDnsName,public_dns: PublicDnsName,public_ip: PublicIpAddress}', full_instances)

for instance in instances:
    print instance['public_ip']

